/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noahc
 */
import java.io.*;
public class CreateEventScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateEventScreen.class.getName());

    /**
     * Creates new form HomeScreen1
     */
    public CreateEventScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drop_month = new javax.swing.JComboBox<>();
        drop_hour = new javax.swing.JComboBox<>();
        drop_day = new javax.swing.JComboBox<>();
        drop_minutes = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        txt_eventName = new javax.swing.JTextField();
        txt_invitees = new javax.swing.JTextField();
        lbl_money = new javax.swing.JLabel();
        txt_moneyNeeded = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        txt_itemsNeeded1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 140, 40));
        jPanel1.setMaximumSize(new java.awt.Dimension(270, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 380));
        jPanel1.setLayout(null);

        drop_month.setBackground(new java.awt.Color(255, 255, 255));
        drop_month.setForeground(new java.awt.Color(0, 0, 0));
        drop_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(drop_month);
        drop_month.setBounds(90, 120, 95, 26);

        drop_hour.setBackground(new java.awt.Color(255, 255, 255));
        drop_hour.setForeground(new java.awt.Color(0, 0, 0));
        drop_hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(drop_hour);
        drop_hour.setBounds(90, 150, 92, 26);

        drop_day.setBackground(new java.awt.Color(255, 255, 255));
        drop_day.setForeground(new java.awt.Color(0, 0, 0));
        drop_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        drop_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drop_dayActionPerformed(evt);
            }
        });
        jPanel1.add(drop_day);
        drop_day.setBounds(200, 120, 76, 26);

        drop_minutes.setBackground(new java.awt.Color(255, 255, 255));
        drop_minutes.setForeground(new java.awt.Color(0, 0, 0));
        drop_minutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ":00", ":15", ":30", ":45" }));
        jPanel1.add(drop_minutes);
        drop_minutes.setBounds(200, 150, 76, 26);

        btn_add.setBackground(new java.awt.Color(210, 110, 10));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add to schedule");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(110, 370, 150, 27);

        txt_eventName.setBackground(new java.awt.Color(255, 255, 255));
        txt_eventName.setForeground(new java.awt.Color(0, 0, 0));
        txt_eventName.setText("Event Title");
        jPanel1.add(txt_eventName);
        txt_eventName.setBounds(100, 210, 169, 26);

        txt_invitees.setBackground(new java.awt.Color(255, 255, 255));
        txt_invitees.setForeground(new java.awt.Color(0, 0, 0));
        txt_invitees.setText("Invitees");
        jPanel1.add(txt_invitees);
        txt_invitees.setBounds(100, 330, 169, 26);

        lbl_money.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbl_money.setForeground(new java.awt.Color(255, 255, 255));
        lbl_money.setText("$");
        jPanel1.add(lbl_money);
        lbl_money.setBounds(90, 260, 7, 15);

        txt_moneyNeeded.setBackground(new java.awt.Color(255, 255, 255));
        txt_moneyNeeded.setForeground(new java.awt.Color(0, 0, 0));
        txt_moneyNeeded.setText("Money Required");
        jPanel1.add(txt_moneyNeeded);
        txt_moneyNeeded.setBounds(100, 250, 169, 26);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Create New Event");
        jPanel1.add(lbl_title);
        lbl_title.setBounds(80, 50, 210, 30);

        btn_home.setBackground(new java.awt.Color(210, 110, 10));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home);
        btn_home.setBounds(20, 10, 76, 27);

        txt_itemsNeeded1.setBackground(new java.awt.Color(255, 255, 255));
        txt_itemsNeeded1.setForeground(new java.awt.Color(0, 0, 0));
        txt_itemsNeeded1.setText("Items Required");
        jPanel1.add(txt_itemsNeeded1);
        txt_itemsNeeded1.setBounds(100, 290, 169, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        HomeScreen homeScreen = new HomeScreen();//initializes the SecondScreen jFrame with the parameter of the user's input, this is to pass it to the other jFrame
        homeScreen.setVisible(true);//sets the secondScreen jFrame as visible
        this.dispose();//kills this jFrame:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void drop_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drop_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drop_dayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateEventScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_home;
    private javax.swing.JComboBox<String> drop_day;
    private javax.swing.JComboBox<String> drop_hour;
    private javax.swing.JComboBox<String> drop_minutes;
    private javax.swing.JComboBox<String> drop_month;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_money;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_eventName;
    private javax.swing.JTextField txt_invitees;
    private javax.swing.JTextField txt_itemsNeeded1;
    private javax.swing.JTextField txt_moneyNeeded;
    // End of variables declaration//GEN-END:variables
}
