/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author derek
 */
public class HomeScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreen.class.getName());

    /**
     * Creates new form HomeScreenReal
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_events = new javax.swing.JList<>();
        lbl_upcoming = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        btn_decline = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_invitations = new javax.swing.JList<>();
        lbl_invitations = new javax.swing.JLabel();
        btn_createevent = new javax.swing.JButton();
        btn_accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 140, 40));
        jPanel1.setMaximumSize(new java.awt.Dimension(270, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 380));
        jPanel1.setLayout(null);

        list_events.setBackground(new java.awt.Color(255, 255, 255));
        list_events.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(list_events);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(60, 120, 250, 100);

        lbl_upcoming.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_upcoming.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upcoming.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_upcoming.setText("Upcoming Events:");
        jPanel1.add(lbl_upcoming);
        lbl_upcoming.setBounds(100, 100, 160, 16);

        btn_logout.setBackground(new java.awt.Color(210, 110, 10));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(20, 10, 76, 27);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Home");
        jPanel1.add(lbl_title);
        lbl_title.setBounds(80, 50, 210, 30);

        btn_decline.setBackground(new java.awt.Color(210, 110, 10));
        btn_decline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_decline.setForeground(new java.awt.Color(255, 255, 255));
        btn_decline.setText("Decline");
        btn_decline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_declineActionPerformed(evt);
            }
        });
        jPanel1.add(btn_decline);
        btn_decline.setBounds(220, 450, 90, 31);

        list_invitations.setBackground(new java.awt.Color(255, 255, 255));
        list_invitations.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(list_invitations);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(60, 330, 250, 100);

        lbl_invitations.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_invitations.setForeground(new java.awt.Color(255, 255, 255));
        lbl_invitations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_invitations.setText("Invitations:");
        jPanel1.add(lbl_invitations);
        lbl_invitations.setBounds(100, 310, 160, 16);

        btn_createevent.setBackground(new java.awt.Color(210, 110, 10));
        btn_createevent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_createevent.setForeground(new java.awt.Color(255, 255, 255));
        btn_createevent.setText("Create Event");
        btn_createevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createeventActionPerformed(evt);
            }
        });
        jPanel1.add(btn_createevent);
        btn_createevent.setBounds(110, 240, 140, 31);

        btn_accept.setBackground(new java.awt.Color(210, 110, 10));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setText("Accept");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accept);
        btn_accept.setBounds(60, 450, 90, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        LoginFrame loginScreen = new loginScreen();//initializes the SecondScreen jFrame with the parameter of the user's input, this is to pass it to the other jFrame
        loginScreen.setVisible(true);//sets the secondScreen jFrame as visible
        this.dispose();//kills this jFrame:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_declineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_declineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_declineActionPerformed

    private void btn_createeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createeventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_createeventActionPerformed

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_createevent;
    private javax.swing.JButton btn_decline;
    private javax.swing.JButton btn_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_invitations;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_upcoming;
    private javax.swing.JList<String> list_events;
    private javax.swing.JList<String> list_invitations;
    // End of variables declaration//GEN-END:variables
}
