/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noahc
 */
import java.io.*;
public class HomeScreen1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreen1.class.getName());

    /**
     * Creates new form HomeScreen1
     */
    public HomeScreen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drop_month = new javax.swing.JComboBox<>();
        drop_hour = new javax.swing.JComboBox<>();
        drop_day = new javax.swing.JComboBox<>();
        drop_minutes = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        txt_eventName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_itemsNeeded = new javax.swing.JTextField();
        lbl_money = new javax.swing.JLabel();
        txt_moneyNeeded = new javax.swing.JTextField();
        lbl_pending = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_pending = new javax.swing.JList<>();
        btn_decline = new javax.swing.JButton();
        btn_accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(270, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 380));
        jPanel1.setLayout(null);

        drop_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(drop_month);
        drop_month.setBounds(54, 17, 92, 22);

        drop_hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(drop_hour);
        drop_hour.setBounds(54, 45, 92, 22);

        drop_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(drop_day);
        drop_day.setBounds(152, 17, 72, 22);

        drop_minutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ":00", ":15", ":30", ":45" }));
        jPanel1.add(drop_minutes);
        drop_minutes.setBounds(152, 45, 72, 22);

        btn_add.setText("Add to schedule");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(80, 180, 116, 23);

        txt_eventName.setText("Event Title");
        jPanel1.add(txt_eventName);
        txt_eventName.setBounds(54, 91, 169, 22);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 75, 270, 10);

        txt_itemsNeeded.setText("Items Required");
        jPanel1.add(txt_itemsNeeded);
        txt_itemsNeeded.setBounds(54, 150, 169, 22);

        lbl_money.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbl_money.setText("$");
        jPanel1.add(lbl_money);
        lbl_money.setBounds(42, 126, 6, 15);

        txt_moneyNeeded.setText("Money Required");
        jPanel1.add(txt_moneyNeeded);
        txt_moneyNeeded.setBounds(54, 119, 169, 22);

        lbl_pending.setText("Pending hangouts:");
        jPanel1.add(lbl_pending);
        lbl_pending.setBounds(60, 220, 160, 16);

        jScrollPane2.setViewportView(list_pending);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 250, 100);

        btn_decline.setText("Decline");
        jPanel1.add(btn_decline);
        btn_decline.setBounds(30, 350, 72, 23);

        btn_accept.setText("Accept");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accept);
        btn_accept.setBounds(160, 350, 72, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_decline;
    private javax.swing.JComboBox<String> drop_day;
    private javax.swing.JComboBox<String> drop_hour;
    private javax.swing.JComboBox<String> drop_minutes;
    private javax.swing.JComboBox<String> drop_month;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_money;
    private javax.swing.JLabel lbl_pending;
    private javax.swing.JList<String> list_pending;
    private javax.swing.JTextField txt_eventName;
    private javax.swing.JTextField txt_itemsNeeded;
    private javax.swing.JTextField txt_moneyNeeded;
    // End of variables declaration//GEN-END:variables
}
