/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author derek
 */
public class HomeScreenReal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreenReal.class.getName());

    /**
     * Creates new form HomeScreenReal
     */
    public HomeScreenReal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_pending = new javax.swing.JList<>();
        lbl_pending1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_pending = new javax.swing.JLabel();
        btn_decline2 = new javax.swing.JButton();
        btn_decline1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_pending1 = new javax.swing.JList<>();
        lbl_pending2 = new javax.swing.JLabel();
        btn_decline3 = new javax.swing.JButton();
        btn_decline4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 140, 40));
        jPanel1.setMaximumSize(new java.awt.Dimension(270, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 380));
        jPanel1.setLayout(null);

        list_pending.setBackground(new java.awt.Color(255, 255, 255));
        list_pending.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(list_pending);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(60, 120, 250, 100);

        lbl_pending1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_pending1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pending1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pending1.setText("Upcoming Events:");
        jPanel1.add(lbl_pending1);
        lbl_pending1.setBounds(100, 100, 160, 16);

        jButton1.setBackground(new java.awt.Color(210, 110, 10));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 10, 76, 27);

        lbl_pending.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_pending.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pending.setText("Home");
        jPanel1.add(lbl_pending);
        lbl_pending.setBounds(70, 50, 210, 30);

        btn_decline2.setBackground(new java.awt.Color(210, 110, 10));
        btn_decline2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_decline2.setForeground(new java.awt.Color(255, 255, 255));
        btn_decline2.setText("Decline");
        btn_decline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decline2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_decline2);
        btn_decline2.setBounds(220, 470, 90, 31);

        btn_decline1.setBackground(new java.awt.Color(210, 110, 10));
        btn_decline1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_decline1.setForeground(new java.awt.Color(255, 255, 255));
        btn_decline1.setText("View & Edit Events");
        btn_decline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decline1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_decline1);
        btn_decline1.setBounds(90, 280, 180, 27);

        list_pending1.setBackground(new java.awt.Color(255, 255, 255));
        list_pending1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(list_pending1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(60, 350, 250, 100);

        lbl_pending2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_pending2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pending2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pending2.setText("Invitations:");
        jPanel1.add(lbl_pending2);
        lbl_pending2.setBounds(100, 330, 160, 16);

        btn_decline3.setBackground(new java.awt.Color(210, 110, 10));
        btn_decline3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_decline3.setForeground(new java.awt.Color(255, 255, 255));
        btn_decline3.setText("Create Event");
        btn_decline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decline3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_decline3);
        btn_decline3.setBounds(110, 240, 140, 31);

        btn_decline4.setBackground(new java.awt.Color(210, 110, 10));
        btn_decline4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_decline4.setForeground(new java.awt.Color(255, 255, 255));
        btn_decline4.setText("Accept");
        btn_decline4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decline4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_decline4);
        btn_decline4.setBounds(60, 470, 90, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_decline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decline2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decline2ActionPerformed

    private void btn_decline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decline1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decline1ActionPerformed

    private void btn_decline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decline3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decline3ActionPerformed

    private void btn_decline4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decline4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decline4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreenReal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decline1;
    private javax.swing.JButton btn_decline2;
    private javax.swing.JButton btn_decline3;
    private javax.swing.JButton btn_decline4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_pending;
    private javax.swing.JLabel lbl_pending1;
    private javax.swing.JLabel lbl_pending2;
    private javax.swing.JList<String> list_pending;
    private javax.swing.JList<String> list_pending1;
    // End of variables declaration//GEN-END:variables
}
